### ISSUE TITLE
warning: case label value is less than minimum value for type

### ISSUE THREAD

**Issue by devvaibhav455** [swri-robotics/swri_console#53] opened 2022-12-06 20:50 UTC
Hi,

I get this warning while building `swri_console_util` from source on Ubuntu 20.04.5 LTS focal on arm64 for ROS2 foxy.

```
Starting >>> swri_prefix_tools
--- stderr: swri_console_util                                                                                                                                                                    
/home/ubuntu/husky_ws2/src/marti_common/swri_console_util/src/progress_bar.cpp: In member function ‘void swri_console_util::ProgressBar::CheckForPause()’:
/home/ubuntu/husky_ws2/src/marti_common/swri_console_util/src/progress_bar.cpp:126:11: warning: case label value is less than minimum value for type
  126 |           case EOF:
      |           ^~~~
---
Finished <<< swri_console_util [4.79s]
```

This is working fine on another system with amd64 architecture.

**Comment by matt-attack** [comment] 2022-12-06 23:37
I'll note this issue likely belongs in marti_common instead. The issue is likely in how char is defined on that platform. Some platforms define a char as signed, others as unsigned (who knows why). Apparently on x86-x64 char is signed and on arm64 it is unsigned. EOF is defined as -1 so it ends up being less than 0, the minimum value of an unsigned char producing this warning.

It would be useful to find out of this type mismatch actually breaks something. Either way one can fix this warning by having ProgressBar::ReadCharFromStdin return a fully specified type of signed char.

**Comment by danthony06** [comment] 2023-09-20 22:24
Fixed via:
https://github.com/swri-robotics/marti_common/pull/718
https://github.com/swri-robotics/marti_common/pull/717

**Closed by danthony06** 2023-09-20 22:24 UTC
